import type { Lang } from '@/lib/preferences'

const en = {
  fontSize: 'Font size',
  color: 'Color',
  autoZone: 'Automatically set time zone',
  autoZoneHint:
    'Reminders, notifications and emails are delivered based on your time zone.',
  timezone: 'Time Zone',
  timezoneHint: 'Current time zone setting.',
  region: 'Language and Region',
  regionHint: 'Display language, region format.',
  voice: 'Voice',
  voiceHint: 'Speech language, speech recognition, sound.',
  mobilePush: 'Mobile push notifications',
  mobilePushHint: 'Receive push notifications on your mobile app.',
  emailNotifications: 'Email notifications',
  emailNotificationsHint: 'Receive email updates.',
  alwaysEmail: 'Always send email notifications',
  alwaysEmailHint:
    'Receive updates by email, even when you’re active on the app.',
  slackNotifications: 'Slack notifications',
  slackHint: 'Receive notifications in your Slack workspace.',
  cookies: 'Cookie settings',
  cookiesHint: 'Customize cookies. See Cookie Notice for details.',
  customize: 'Customize',
  history: 'History',
  historyHint: 'Number of days to keep history.',
  days: 'days',
  payout: 'Payout invoice info',
  payoutHint:
    'Optional. Information added here, such as your business name, address, VAT number, etc. will be included when generating a payout invoice.',
  payoutPlaceholder: 'Enter your business name, address, VAT number, etc.',
  paymentMethod: 'Payment method',
  default: 'Default',
  profile: 'Profile Details',
  signIn: 'Sign-in Method',
  connected: 'Connected Accounts',
  emails: 'Email Preferences',
  notifications: 'Notifications',
  deactivate: 'Deactivate account',
  firstName: 'First Name',
  lastName: 'Last Name',
  phone: 'Contact Phone',
  skill: 'Skill',
  company: 'Company',
  website: 'Company Site',
  country: 'Country',
  language: 'Language',
  status: 'Status',
  active: 'Active',
  email: 'Email Address',
  password: 'Password',
  secure: 'Secure Your Account',
  secureHint:
    "Two-factor authentication adds an extra layer of security to your account. To log in, in addition you'll need to provide a 6 digit code.",
  connectedHint:
    "Two-factor authentication adds an extra layer of security to your account. To log in, you'll need to provide a 4 digit amazing code. Learn More",
  enable: 'Enable',
  disable: 'Disable',
  cancel: 'Cancel',
  save: 'Save Changes',
  confirm: 'I confirm my account deactivation',
  deactivateHint: 'You Are Deactivating Your Account',
  deactivateDescription:
    'For extra security, this requires you to confirm your email or phone number when you reset your password. Learn more',
  payment: 'Successful Payments',
  fees: 'Fee Collection',
  disputes: 'Customer Payment Dispute',
  refunds: 'Refund Alerts',
  invoices: 'Invoice Payments',
  webhooks: 'Webhook API Endpoints',
  paymentHint: 'Receive a notification for every successful payment.',
  feesHint: 'Receive a notification each time you collect a fee from sales.',
  disputesHint: 'Receive a notification if the customer disputes the payment.',
  refundsHint: 'Receive a notification if a payment is stated as risky.',
  invoicesHint:
    'Receive a notification if a customer sends an incorrect amount to pay their invoice.',
  webhooksHint:
    'Receive notifications for consistently failing webhook API endpoints.',
  billing: 'Billing Updates',
  members: 'New Team Members',
  projects: 'Completed Projects',
  newsletters: 'Newsletters',
  emailChannel: 'Email',
  phoneChannel: 'Phone',
  overview: 'Overview',
  settings: 'Settings',
  security: 'Security',
  billingTab: 'Billing',
  statements: 'Statements',
  referrals: 'Referrals',
  api: 'API Keys',
  logs: 'Logs',
  follow: 'Follow',
  hire: 'Hire Me',
  theme: 'Theme',
  timeLanguage: 'Time and language',
  privacy: 'Privacy',
  paymentTab: 'Payment',
  plugins: 'Plugins',
  accountSecurity: 'Account security',
  name: 'Name',
  support: 'Support',
  supportAccess: 'Support access',
  supportHint:
    'Grant SnowUI support temporary access to your account so we can troubleshoot problems or recover content on your behalf. You can revoke access at any time.',
  passwordHint: 'Set a permanent password to login to your account.',
  twoFactor: '2-step verification',
  twoFactorHint:
    'Add an additional layer of security to your account during sign in.',
  logout: 'Log out of all devices',
  logoutHint:
    'Log out of all other active sessions on other devices besides this one.',
  delete: 'Delete my account',
  deleteHint:
    'Permanently delete the account and remove access from all devices.',
  on: 'On',
  off: 'Off',
  close: 'Close settings',
  editName: 'Edit name',
  openPanel: 'Open settings panel',
  analytics: 'Usage analytics',
  analyticsHint: 'Share usage analytics to improve SnowUI.',
  plan: 'Plan',
  free: 'Free',
  method: 'Payment method',
  noMethod: 'No payment method',
}
const ru: typeof en = {
  ...en,
  fontSize: 'Размер шрифта',
  color: 'Цвет',
  autoZone: 'Определять часовой пояс автоматически',
  autoZoneHint: 'Напоминания, уведомления и письма учитывают ваш часовой пояс.',
  timezone: 'Часовой пояс',
  timezoneHint: 'Текущий часовой пояс.',
  region: 'Язык и регион',
  regionHint: 'Язык интерфейса и формат региона.',
  voice: 'Голос',
  voiceHint: 'Язык речи, распознавание речи и звук.',
  mobilePush: 'Мобильные push-уведомления',
  mobilePushHint: 'Получать push-уведомления в мобильном приложении.',
  emailNotifications: 'Email-уведомления',
  emailNotificationsHint: 'Получать обновления по почте.',
  alwaysEmail: 'Всегда отправлять email-уведомления',
  alwaysEmailHint: 'Получать письма, даже когда приложение открыто.',
  slackNotifications: 'Уведомления Slack',
  slackHint: 'Получать уведомления в рабочем пространстве Slack.',
  cookies: 'Настройки cookie',
  cookiesHint: 'Настроить cookie. Подробнее — в уведомлении о cookie.',
  customize: 'Настроить',
  history: 'История',
  historyHint: 'Сколько дней хранить историю.',
  days: 'дней',
  payout: 'Данные для счёта',
  payoutHint:
    'Необязательно. Название компании, адрес, ИНН и другие данные попадут в счёт.',
  payoutPlaceholder: 'Название компании, адрес, ИНН и другие данные',
  paymentMethod: 'Способ оплаты',
  default: 'Основной',
  profile: 'Данные профиля',
  signIn: 'Способ входа',
  connected: 'Подключённые аккаунты',
  emails: 'Email-уведомления',
  notifications: 'Уведомления',
  deactivate: 'Деактивация аккаунта',
  firstName: 'Имя',
  lastName: 'Фамилия',
  phone: 'Телефон',
  skill: 'Навыки',
  company: 'Компания',
  website: 'Сайт компании',
  country: 'Страна',
  language: 'Язык',
  status: 'Статус',
  active: 'Активен',
  email: 'Email',
  password: 'Пароль',
  secure: 'Защитите аккаунт',
  secureHint:
    'Двухфакторная аутентификация добавляет ещё один уровень защиты аккаунта. Для входа потребуется шестизначный код.',
  connectedHint:
    'Двухфакторная аутентификация добавляет дополнительный уровень защиты аккаунта. Для входа потребуется четырёхзначный код. Подробнее',
  enable: 'Включить',
  disable: 'Выключить',
  cancel: 'Отмена',
  save: 'Сохранить изменения',
  confirm: 'Я подтверждаю деактивацию аккаунта',
  deactivateHint: 'Вы деактивируете свой аккаунт',
  deactivateDescription:
    'Для дополнительной безопасности подтвердите своё намерение.',
  payment: 'Успешные платежи',
  fees: 'Сбор комиссии',
  disputes: 'Споры по платежам',
  refunds: 'Возвраты',
  invoices: 'Оплата счетов',
  webhooks: 'Webhook API',
  paymentHint: 'Уведомлять о каждом успешном платеже.',
  feesHint: 'Уведомлять о получении комиссии.',
  disputesHint: 'Уведомлять об оспаривании платежа.',
  refundsHint: 'Уведомлять о рискованном платеже.',
  invoicesHint: 'Уведомлять о неверной сумме оплаты счёта.',
  webhooksHint: 'Уведомлять о сбоях webhook API.',
  billing: 'Обновления оплаты',
  members: 'Новые участники',
  projects: 'Завершённые проекты',
  newsletters: 'Рассылки',
  emailChannel: 'Email',
  phoneChannel: 'Телефон',
  overview: 'Обзор',
  settings: 'Настройки',
  security: 'Безопасность',
  billingTab: 'Оплата',
  statements: 'Выписки',
  referrals: 'Рефералы',
  api: 'API-ключи',
  logs: 'Журнал',
  follow: 'Подписаться',
  hire: 'Нанять',
  theme: 'Тема',
  timeLanguage: 'Время и язык',
  privacy: 'Конфиденциальность',
  paymentTab: 'Оплата',
  plugins: 'Плагины',
  accountSecurity: 'Безопасность аккаунта',
  name: 'Имя',
  support: 'Поддержка',
  supportAccess: 'Доступ поддержки',
  supportHint:
    'Разрешите поддержке SnowUI временный доступ для решения проблем или восстановления данных. Доступ можно отозвать в любое время.',
  passwordHint: 'Установите постоянный пароль для входа.',
  twoFactor: 'Двухэтапная проверка',
  twoFactorHint: 'Добавьте ещё один уровень защиты при входе.',
  logout: 'Выйти на всех устройствах',
  logoutHint: 'Завершить остальные активные сеансы.',
  delete: 'Удалить аккаунт',
  deleteHint: 'Удалить аккаунт и закрыть доступ со всех устройств.',
  on: 'Вкл.',
  off: 'Выкл.',
  close: 'Закрыть настройки',
  editName: 'Изменить имя',
  openPanel: 'Открыть панель настроек',
  analytics: 'Аналитика использования',
  analyticsHint: 'Помочь улучшить SnowUI, делясь аналитикой.',
  plan: 'План',
  free: 'Бесплатный',
  method: 'Способ оплаты',
  noMethod: 'Способ оплаты не задан',
}
export const getSettingsCopy = (lang: Lang) => (lang === 'ru' ? ru : en)
