export const ROLES = {
	avatar: "figure",
	badge: "status",
	breadcrumbs: "navigation",
	breadcrumbsItem: "link",
	button: "button",
	card: "article",
	dialog: "dialog",
	dialogTitle: "heading",
	dropdown: "listbox",
	dropdownItem: "option",
	dropdownList: "list",
	icon: "img",
	input: "textbox",
	link: "link",
	search: "search",
	slider: "slider",
	textarea: "textbox",
	kbd: "definition",
	line: "separator",
	notification: "alert",
	searchPopup: "dialog",
	statusBadge: "status",
	tag: "listitem",
	tooltip: "tooltip",
};
