import { existsSync, readFileSync } from 'node:fs'
import { dirname, join, posix, relative, resolve } from 'node:path'
import { Node, Project, type SourceFile } from 'ts-morph'
import type {
  BuildContext,
  ExtraItem,
  GroupRule,
  ItemType,
  RegistryConfig,
} from './config'
import { type Binding, type Edge, loadGraph, type ModuleGraph } from './graph'
import {
  baseName,
  camelCase,
  kebabCase,
  listFiles,
  matchesAny,
  RegistryError,
  relativeSpecifier,
  sorted,
  toPosix,
  withoutExtension,
} from './util'

/** An item of the committed manifest (`manifest.json`). */
export interface ManifestItem {
  name: string
  type: ItemType
  title: string
  /** Only for items defined in the config (the rest get one at build time). */
  description?: string
  /** Source files, relative to the source root. */
  files?: string[]
  /** Ships the licence text (`LICENSE` in the target root). */
  license?: boolean
  /** npm packages (the build adds the version ranges). */
  dependencies?: string[]
  /** Items of this registry, or `@namespace/name` / URLs of others. */
  registryDependencies?: string[]
  /** Import path below the target root (`components/Button`). */
  import?: string
  /** Exported values and types of `import`. */
  exports?: string[]
  types?: string[]
  /** Storybook id of the item's docs page (`components-button`). */
  docs?: string
  /** Other registry-item fields of items defined in the config. */
  extra?: Omit<
    ExtraItem,
    | 'name'
    | 'type'
    | 'title'
    | 'description'
    | 'dependencies'
    | 'registryDependencies'
  >
}

export interface Manifest {
  $comment: string
  name: string
  namespace: string
  homepage: string
  baseUrl: string
  /** The source package: npm name and repository path of its sources. */
  package: { name: string; source: string }
  target: string
  items: ManifestItem[]
}

/** A text replacement in a source file. */
export interface TextEdit {
  start: number
  end: number
  text: string
}

export interface PackageJson {
  name: string
  version: string
  dependencies?: Record<string, string>
  peerDependencies?: Record<string, string>
  devDependencies?: Record<string, string>
}

export interface Plan {
  manifest: Manifest
  /** Item descriptions (docs page intro, JSDoc, config), for the build. */
  descriptions: Map<string, string>
  graph: ModuleGraph
  /** Import rewrites per shipped file (imports through unshipped barrels). */
  rewrites: Map<string, TextEdit[]>
  /** Absolute paths used by the build. */
  paths: { configDir: string; packageDir: string; srcDir: string }
  packageJson: PackageJson
}

const COMMENT =
  'Generated by `bun run registry` (packages/registry) from the sources of the package; do not edit. CI fails when it is out of date.'

const isComponentModule = (file: string) =>
  /\.tsx$/.test(file) && /^[A-Z]/.test(posix.basename(file))

/** Storybook's id of a title: `Components/Input/Checkbox` → `components-input-checkbox`. */
export const storyId = (title: string) =>
  title
    .toLowerCase()
    .replace(/[ ’–—―′¿'`~!@#$%^&*()_|+\-=?;:'",.<>{}[\]\\/]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '')

/** The context of a manifest or a build rendered for `baseUrl`. */
export function buildContext(
  config: RegistryConfig,
  baseUrl: string,
  version: string,
): BuildContext {
  const url = (name: string) => `${baseUrl}/${name}.json`
  return {
    baseUrl,
    url,
    ref: (name) =>
      config.dependencyStyle === 'url'
        ? url(name)
        : `${config.namespace}/${name}`,
    namespace: config.namespace,
    version,
  }
}

/**
 * Plans the registry: loads the source graph, groups files into items,
 * decides which barrels ship, computes the import rewrites and every item's
 * dependencies. Throws a `RegistryError` listing every problem found.
 */
export function createPlan(config: RegistryConfig, configDir: string): Plan {
  const packageDir = resolve(configDir, config.package)
  const srcDir = resolve(packageDir, config.srcDir)
  const packageJson = JSON.parse(
    readFileSync(join(packageDir, 'package.json'), 'utf8'),
  ) as PackageJson
  const all = listFiles(srcDir)
  const isSource = (file: string) =>
    /\.tsx?$/.test(file) && !/\.d\.ts$/.test(file)
  const excluded = all.filter(
    (file) => isSource(file) && matchesAny(file, config.exclude),
  )
  const files = all.filter(
    (file) => isSource(file) && !matchesAny(file, config.exclude),
  )
  const graph = loadGraph(srcDir, files, excluded)
  const { modules } = graph
  const problems: string[] = []
  const mod = (file: string) => {
    const found = modules.get(file)
    if (!found) throw new Error(`Unknown module ${file}`)
    return found
  }

  // --- Barrel resolution -------------------------------------------------

  const exportsName = (file: string, name: string) =>
    mod(file).source.getExportedDeclarations().has(name)

  /** The module a barrel's `name` comes from (one level). */
  const barrelSource = (barrel: string, name: string): string | undefined => {
    for (const edge of mod(barrel).edges) {
      if (edge.kind !== 'export' || !edge.file) continue
      if (edge.bindings) {
        const binding = edge.bindings.find((b) => (b.alias ?? b.name) === name)
        if (binding) {
          if (binding.alias) {
            problems.push(
              `${barrel} renames "${binding.name}" to "${binding.alias}"; renamed re-exports can't be rewritten`,
            )
          }
          return edge.file
        }
      } else if (!edge.namespace && exportsName(edge.file, name)) {
        return edge.file
      }
    }
    return undefined
  }

  /** Follows `name` through barrels that aren't shipped as they are. */
  const resolveThrough = (
    file: string,
    name: string,
    shipped: ReadonlySet<string>,
  ): string => {
    const module = mod(file)
    if (!module.barrel || shipped.has(file)) return file
    const next = barrelSource(file, name)
    if (!next) {
      problems.push(`${file} does not export "${name}"`)
      return file
    }
    return resolveThrough(next, name, shipped)
  }

  /** The modules an edge depends on, looking through unshipped barrels. */
  const edgeTargets = (edge: Edge, shipped: ReadonlySet<string>): string[] => {
    const file = edge.file
    if (!file) return []
    const target = mod(file)
    if (!target.barrel || shipped.has(file)) return [file]
    if (!edge.bindings) {
      return target.edges.flatMap((e) => edgeTargets(e, shipped))
    }
    return edge.bindings.map((b) => resolveThrough(file, b.name, shipped))
  }

  // --- Items from the group rules ---------------------------------------

  interface Draft {
    name: string
    type: ItemType
    title: string
    description?: string
    files: Set<string>
    /** The module whose docs describe the item. */
    main?: string
    /** The component directory, when the item is a whole directory. */
    dir?: string
    import?: string
  }
  const drafts = new Map<string, Draft>()
  const owners = new Map<string, Set<string>>()
  const own = (draft: Draft, file: string) => {
    draft.files.add(file)
    if (!owners.has(file)) owners.set(file, new Set())
    owners.get(file)?.add(draft.name)
  }
  const addDraft = (draft: Draft) => {
    if (drafts.has(draft.name)) {
      problems.push(`Two items are named "${draft.name}"`)
    } else {
      drafts.set(draft.name, draft)
    }
    return draft
  }
  const nonBarrels = files.filter((file) => !mod(file).barrel)
  const unassigned = (file: string) => !owners.has(file)

  const componentDir = (path: string, dir: string, type: ItemType) => {
    const members = files.filter((file) => file.startsWith(`${path}/`))
    const barrel = members.find(
      (file) =>
        /^index\.tsx?$/.test(posix.basename(file)) &&
        posix.dirname(file) === path &&
        mod(file).barrel,
    )
    const local = members.filter((file) => !mod(file).barrel)
    const components = barrel
      ? sorted(
          mod(barrel)
            .edges.filter(
              (e) => e.kind === 'export' && e.file && local.includes(e.file),
            )
            .map((e) => e.file ?? '')
            .filter(isComponentModule),
        )
      : local.filter(
          (file) => posix.dirname(file) === path && isComponentModule(file),
        )
    if (!components.length) {
      problems.push(
        `${path}: no component module (a PascalCase .tsx file${barrel ? ` re-exported by ${barrel}` : ''})`,
      )
      return
    }
    if (components.length === 1) {
      const draft = addDraft({
        name: kebabCase(dir),
        type,
        title: baseName(components[0]),
        files: new Set(),
        main: components[0],
        dir: path,
        import: withoutExtension(components[0]),
      })
      for (const file of local) own(draft, file)
      return
    }
    // Several components: one item each, with the private files it reaches.
    const componentSet = new Set(components)
    const localSet = new Set(local)
    for (const component of components) {
      const draft = addDraft({
        name: kebabCase(baseName(component)),
        type,
        title: baseName(component),
        files: new Set(),
        main: component,
        import: withoutExtension(component),
      })
      const queue = [component]
      const seen = new Set(queue)
      while (queue.length) {
        const file = queue.shift() ?? ''
        own(draft, file)
        for (const edge of mod(file).edges) {
          for (const target of edgeTargets(edge, new Set())) {
            if (
              localSet.has(target) &&
              !componentSet.has(target) &&
              !seen.has(target)
            ) {
              seen.add(target)
              queue.push(target)
            }
          }
        }
      }
    }
    for (const file of local) {
      if (unassigned(file)) {
        problems.push(`${file} is not imported by any component of ${path}`)
      }
    }
  }

  const applyRule = (rule: GroupRule) => {
    if (rule.kind === 'components') {
      const prefix = `${rule.dir}/`
      const dirs = sorted(
        files
          .filter((file) => file.startsWith(prefix))
          .map((file) => file.slice(prefix.length).split('/'))
          .filter((parts) => parts.length > 1)
          .map((parts) => parts[0]),
      )
      for (const dir of dirs) {
        componentDir(`${prefix}${dir}`, dir, rule.type ?? 'registry:ui')
      }
    } else if (rule.kind === 'each') {
      for (const file of nonBarrels) {
        if (!unassigned(file) || !matchesAny(file, rule.files)) continue
        const name = kebabCase(baseName(file))
        own(
          addDraft({
            name,
            type: rule.type,
            title:
              rule.type === 'registry:hook' ? camelCase(name) : baseName(file),
            files: new Set(),
            main: file,
            import: withoutExtension(file),
          }),
          file,
        )
      }
    } else {
      const matched = nonBarrels.filter(
        (file) => unassigned(file) && matchesAny(file, rule.files),
      )
      if (!matched.length) {
        problems.push(
          `Group "${rule.name}" matches no files (${rule.files.join(', ')})`,
        )
        return
      }
      const draft = addDraft({
        name: rule.name,
        type: rule.type,
        title: rule.title ?? rule.name,
        description: rule.description,
        files: new Set(),
        import: rule.import,
      })
      for (const file of matched) own(draft, file)
    }
  }

  for (const rule of config.groups) applyRule(rule)

  for (const file of nonBarrels) {
    if (unassigned(file)) {
      problems.push(
        `${file} belongs to no item: add it to a group in registry.config.ts (or exclude it)`,
      )
    }
  }

  // --- Barrels ----------------------------------------------------------

  // A barrel ships with the item that holds everything it re-exports (e.g.
  // components/Button/index.ts with the Button item); the others (package
  // entry points, directories of several components) are rewritten away.
  const shipped = new Set<string>()
  const barrels = files.filter((file) => mod(file).barrel)
  const decided = new Set<string>()
  let progress = true
  while (progress) {
    progress = false
    for (const barrel of barrels) {
      if (decided.has(barrel)) continue
      const targets = mod(barrel)
        .edges.map((e) => e.file)
        .filter((file): file is string => !!file)
      if (targets.some((t) => mod(t).barrel && !decided.has(t))) continue
      decided.add(barrel)
      progress = true
      let common: Set<string> | undefined
      for (const target of targets) {
        const targetOwners = owners.get(target) ?? new Set<string>()
        common = common
          ? new Set([...common].filter((o) => targetOwners.has(o)))
          : new Set(targetOwners)
      }
      const owner = common && sorted(common)[0]
      const draft = owner ? drafts.get(owner) : undefined
      if (draft) {
        shipped.add(barrel)
        own(draft, barrel)
        if (draft.dir === posix.dirname(barrel)) draft.import = draft.dir
      }
    }
  }

  // --- Rewrites, dependencies --------------------------------------------

  const rewriteImport = (file: string, edge: Edge): TextEdit => {
    const groups = new Map<string, Binding[]>()
    for (const binding of edge.bindings ?? []) {
      const target = resolveThrough(edge.file ?? '', binding.name, shipped)
      if (!groups.has(target)) groups.set(target, [])
      groups.get(target)?.push(binding)
    }
    const q = edge.quote
    const text = [...groups]
      .map(([target, bindings]) => {
        // `import type { A }` rather than `import { type A }`, which leaves
        // an empty import behind with verbatimModuleSyntax.
        const typeOnly = edge.typeOnly || bindings.every((b) => b.typeOnly)
        const names = bindings
          .map(
            (b) =>
              `${b.typeOnly && !typeOnly ? 'type ' : ''}${b.name}${b.alias ? ` as ${b.alias}` : ''}`,
          )
          .join(', ')
        return `import ${typeOnly ? 'type ' : ''}{ ${names} } from ${q}${relativeSpecifier(file, target)}${q}`
      })
      .join('\n')
    return { start: edge.start, end: edge.end, text }
  }

  const rewrites = new Map<string, TextEdit[]>()
  const registryDeps = new Map<string, Set<string>>()
  const npmDeps = new Map<string, Set<string>>()
  const ignored = new Set(config.ignoreDependencies)

  for (const draft of drafts.values()) {
    const deps = new Set<string>()
    const packages = new Set<string>()
    for (const file of sorted(draft.files)) {
      for (const edge of mod(file).edges) {
        if (edge.pkg) {
          if (!ignored.has(edge.pkg)) packages.add(edge.pkg)
          continue
        }
        if (!edge.file) continue
        let targets: string[]
        if (mod(edge.file).barrel && !shipped.has(edge.file)) {
          if (
            edge.kind === 'export' ||
            edge.namespace ||
            edge.defaultImport ||
            !edge.bindings
          ) {
            problems.push(
              `${file}: "${edge.specifier}" is a barrel that ships with no single item; import the modules it re-exports by name`,
            )
            continue
          }
          const edits = rewrites.get(file) ?? []
          if (!edits.some((e) => e.start === edge.start)) {
            edits.push(rewriteImport(file, edge))
          }
          rewrites.set(file, edits)
          targets = edgeTargets(edge, shipped)
        } else {
          targets = [edge.file]
        }
        for (const target of targets) {
          const targetOwners = owners.get(target)
          if (!targetOwners?.size) {
            problems.push(`${file} imports ${target}, which ships with no item`)
            continue
          }
          if (targetOwners.has(draft.name)) continue
          if (targetOwners.size > 1) {
            problems.push(
              `${file} (${draft.name}) imports ${target}, which ships with several items (${sorted(targetOwners).join(', ')}): give it an item of its own`,
            )
            continue
          }
          deps.add([...targetOwners][0])
        }
      }
    }
    registryDeps.set(draft.name, deps)
    npmDeps.set(draft.name, packages)
  }

  // Item-level cycles would make the CLI resolve items in circles.
  const visiting = new Set<string>()
  const done = new Set<string>()
  const visit = (name: string, path: string[]) => {
    if (done.has(name)) return
    if (visiting.has(name)) {
      problems.push(
        `Items depend on each other in a cycle: ${[...path, name].join(' → ')}`,
      )
      return
    }
    visiting.add(name)
    for (const dep of registryDeps.get(name) ?? []) visit(dep, [...path, name])
    visiting.delete(name)
    done.add(name)
  }
  for (const name of drafts.keys()) visit(name, [])

  // --- Metadata -----------------------------------------------------------

  const closure = (name: string): Set<string> => {
    const seen = new Set<string>([name])
    const queue = [name]
    while (queue.length) {
      for (const dep of registryDeps.get(queue.shift() ?? '') ?? []) {
        if (!seen.has(dep)) {
          seen.add(dep)
          queue.push(dep)
        }
      }
    }
    return seen
  }
  const licenseItem = config.license.file ? config.license.item : undefined
  if (licenseItem && !drafts.has(licenseItem)) {
    problems.push(`license.item "${licenseItem}" is not an item`)
  }

  // Stories are parsed on their own (syntax only): adding files to the
  // graph's project would rebuild its program.
  const storiesProject = new Project({
    skipAddingFilesFromTsConfig: true,
    compilerOptions: { noLib: true, noResolve: true },
  })
  const docsOf = (file: string): { docs?: string } => {
    const stem = withoutExtension(file)
    const candidates = [
      `${stem}.stories.tsx`,
      `${stem}.stories.ts`,
      ...all.filter(
        (f) =>
          posix.dirname(f) === posix.dirname(file) &&
          /\.stories\.tsx?$/.test(f),
      ),
    ]
    const stories = candidates.find((f) => existsSync(join(srcDir, f)))
    if (!stories) return {}
    const title = storiesTitle(
      storiesProject.addSourceFileAtPath(join(srcDir, stories)),
    )
    return title ? { docs: storyId(title) } : {}
  }

  /** The first sentences of the intro of the module's usage page. */
  const mdxIntro = (file: string) => {
    const mdx = join(srcDir, `${withoutExtension(file)}.mdx`)
    return existsSync(mdx)
      ? firstParagraph(readFileSync(mdx, 'utf8'))
      : undefined
  }

  // Descriptions come from the usage pages and JSDoc, which change often:
  // they are rendered at build time, not committed with the manifest.
  const descriptions = new Map<string, string>()
  const items: ManifestItem[] = []
  for (const draft of drafts.values()) {
    const entry = draft.import
      ? [
          `${draft.import}.ts`,
          `${draft.import}.tsx`,
          `${draft.import}/index.ts`,
          `${draft.import}/index.tsx`,
        ].find((f) => draft.files.has(f))
      : undefined
    const { values, types } = entry
      ? exportsOf(mod(entry).source)
      : { values: [], types: [] }
    const main = draft.main ? mod(draft.main).source : undefined
    descriptions.set(
      draft.name,
      draft.description ??
        (draft.main && mdxIntro(draft.main)) ??
        (main && describe(main, draft.title)) ??
        `${draft.title} ${draft.type === 'registry:hook' ? 'hook' : 'component'} from ${packageJson.name}.`,
    )
    items.push({
      name: draft.name,
      type: draft.type,
      title: draft.title,
      ...(draft.description ? { description: draft.description } : {}),
      files: sorted(draft.files),
      ...(licenseItem &&
      (draft.name === licenseItem || !closure(draft.name).has(licenseItem))
        ? { license: true }
        : {}),
      dependencies: sorted(npmDeps.get(draft.name) ?? []),
      registryDependencies: sorted(registryDeps.get(draft.name) ?? []),
      ...(draft.import ? { import: draft.import } : {}),
      ...(values.length ? { exports: values } : {}),
      ...(types.length ? { types } : {}),
      ...(draft.main ? docsOf(draft.main) : {}),
    })
  }

  const context = buildContext(config, config.baseUrl, packageJson.version)
  const names = new Set(items.map((i) => i.name))
  const generated = items.map(({ name, type }) => ({ name, type }))
  for (const extra of config.extraItems?.({ ...context, items: generated }) ??
    []) {
    const {
      name,
      type,
      title,
      description,
      dependencies,
      registryDependencies,
      ...rest
    } = extra
    if (names.has(name)) problems.push(`Two items are named "${name}"`)
    names.add(name)
    descriptions.set(name, description ?? title ?? name)
    items.push({
      name,
      type: type as ItemType,
      title: title ?? name,
      ...(description ? { description } : {}),
      ...(dependencies?.length ? { dependencies } : {}),
      ...(registryDependencies?.length ? { registryDependencies } : {}),
      ...(Object.keys(rest).length ? { extra: rest } : {}),
    })
  }
  for (const item of items) {
    for (const dep of item.registryDependencies ?? []) {
      if (!dep.startsWith('@') && !dep.includes('://') && !names.has(dep)) {
        problems.push(`${item.name} depends on "${dep}", which is not an item`)
      }
    }
  }
  if (names.has('registry') || names.has('index')) {
    problems.push(
      '"registry" and "index" are reserved: the catalog is /r/registry.json',
    )
  }

  if (problems.length) throw new RegistryError(sorted(problems))

  return {
    manifest: {
      $comment: COMMENT,
      name: config.name,
      namespace: config.namespace,
      homepage: config.homepage,
      baseUrl: config.baseUrl,
      package: { name: packageJson.name, source: repoPath(srcDir) },
      target: config.target,
      items,
    },
    descriptions,
    graph,
    rewrites,
    paths: { configDir, packageDir, srcDir },
    packageJson,
  }
}

/** `path` relative to the repository root (the closest `.git`), posix. */
export function repoPath(path: string): string {
  let dir = path
  while (!existsSync(join(dir, '.git'))) {
    const parent = dirname(dir)
    if (parent === dir) return toPosix(path)
    dir = parent
  }
  return toPosix(relative(dir, path))
}

/**
 * The first sentences (up to about 200 characters) of the first paragraph
 * of an MDX page, as plain text: the page's intro after its imports and
 * blocks.
 */
export function firstParagraph(mdx: string): string | undefined {
  let fence = false
  const paragraph: string[] = []
  for (const raw of mdx.split('\n')) {
    const line = raw.trim()
    if (line.startsWith('```')) {
      fence = !fence
      if (paragraph.length) break
      continue
    }
    if (fence) continue
    if (!line || /^(import |export |<|#|\{\/\*|>|- |\* |\|)/.test(line)) {
      if (paragraph.length) break
      continue
    }
    paragraph.push(line)
  }
  if (!paragraph.length) return undefined
  const text = paragraph
    .join(' ')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/\s+/g, ' ')
    .trim()
  const sentences = text.match(/[^.!?]+[.!?]+(?=\s|$)|[^.!?]+$/g) ?? [text]
  let result = ''
  for (const sentence of sentences) {
    if (result && (result + sentence).length > 200) break
    result += sentence
  }
  return result.trim()
}

/** The exported values and types of a module, sorted. */
function exportsOf(source: SourceFile) {
  const values: string[] = []
  const types: string[] = []
  for (const [name, declarations] of source.getExportedDeclarations()) {
    const isType = declarations.every(
      (d) => Node.isTypeAliasDeclaration(d) || Node.isInterfaceDeclaration(d),
    )
    ;(isType ? types : values).push(name)
  }
  return { values: sorted(values), types: sorted(types) }
}

/**
 * The first paragraph of the JSDoc on the exported declaration named `name`,
 * as one line.
 */
function describe(source: SourceFile, name: string): string | undefined {
  for (const declaration of source.getExportedDeclarations().get(name) ?? []) {
    const host = Node.isVariableDeclaration(declaration)
      ? declaration.getVariableStatement()
      : declaration
    if (!host || !Node.isJSDocable(host)) continue
    const docs = host.getJsDocs()
    const text = docs[docs.length - 1]?.getDescription().trim()
    if (text)
      return text
        .split(/\n\s*\n/)[0]
        .replace(/\s+/g, ' ')
        .trim()
  }
  return undefined
}

/** The `title` of a stories file's default export (CSF), syntactically. */
function storiesTitle(source: SourceFile): string | undefined {
  const unwrap = (node: Node | undefined): Node | undefined => {
    if (!node) return undefined
    if (Node.isSatisfiesExpression(node) || Node.isAsExpression(node)) {
      return unwrap(node.getExpression())
    }
    if (Node.isIdentifier(node)) {
      return unwrap(
        source.getVariableDeclaration(node.getText())?.getInitializer(),
      )
    }
    return node
  }
  const assignment = source.getExportAssignment((a) => !a.isExportEquals())
  const value = unwrap(
    assignment?.getExpression() ??
      source.getVariableDeclaration('meta')?.getInitializer(),
  )
  if (!value || !Node.isObjectLiteralExpression(value)) return undefined
  const title = value.getProperty('title')
  if (!title || !Node.isPropertyAssignment(title)) return undefined
  const initializer = title.getInitializer()
  return initializer && Node.isStringLiteral(initializer)
    ? initializer.getLiteralValue()
    : undefined
}
