/*
 * Generated by `bun run tokens` (Terrazzo, scripts/terrazzo-plugin-snow-ui.ts)
 * from tokens/*.tokens.json. Do not edit: change the tokens and regenerate.
 */

/** A colour token: `--color-<name>`, `bg-<name>`, `text-<name>`… */
export interface ColorToken {
  /** Tailwind colour name: `bg-<name>`, `text-<name>`, `border-<name>`… */
  name: string
  /** Figma variable name ("—" for library additions). */
  figma: string
  /** CSS value in the light mode. */
  light: string
  /** CSS value in the dark mode. */
  dark: string
  /** Swatch class; written out so Tailwind generates it. */
  swatch: string
  /** Computed light/dark colours, for tokens whose value is a formula or an alias. */
  resolved?: { light: string; dark: string }
  /**
   * Computed light/dark colours with more contrast (`prefers-contrast:
   * more`, `data-contrast="more"`), for the tokens that change with it.
   */
  contrastMore?: { light: string; dark: string }
  note?: string
}

export type TextSize = 12 | 14 | 16 | 18 | 24 | 32 | 48 | 64

export interface TextStyle {
  /** `size` prop of `Typography`. */
  size: TextSize
  /** Line height in px. */
  lineHeight: number
  /** Font weights of the Figma styles of this size (Regular, Semibold). */
  weights: number[]
  /** Tailwind utility (sets font size and line height). */
  utility: string
}

export interface EffectToken {
  /** CSS variable. */
  variable: string
  figma: string
  value: string
  /** Tailwind utility; written out so Tailwind generates it. */
  utility: string
  note?: string
}

export const colorTokens: ColorToken[] = [
  {
    name: 'primary',
    figma: 'Primary',
    light: '#000',
    dark: '#adadfb',
    swatch: 'bg-primary',
    note: 'Figma alias: Black/100% in SnowUI-Light, Secondary/Indigo in SnowUI-Dark.',
  },
  {
    name: 'primary-hover',
    figma: 'Primary + White/20%',
    light: 'color-mix(in srgb, var(--color-primary), var(--color-white) 20%)',
    dark: 'color-mix(in srgb, var(--color-primary), var(--color-white) 20%)',
    swatch: 'bg-primary-hover',
    resolved: {
      light: '#333',
      dark: '#8a8ac9',
    },
    note: "Primary under a White/20% overlay: Figma's Filled Button hover.",
  },
  {
    name: 'primary-hover-strong',
    figma: 'Primary + White/40%',
    light: 'color-mix(in srgb, var(--color-primary), var(--color-white) 40%)',
    dark: 'color-mix(in srgb, var(--color-primary), var(--color-white) 40%)',
    swatch: 'bg-primary-hover-strong',
    resolved: {
      light: '#666',
      dark: '#686897',
    },
    note: 'Primary under a White/40% overlay: checked Checkbox / Radio / Switch hover.',
  },
  {
    name: 'black',
    figma: 'Black/100%',
    light: '#000',
    dark: '#fff',
    swatch: 'bg-black',
  },
  {
    name: 'black-80',
    figma: 'Black/80%',
    light: 'rgb(0 0 0 / 0.8)',
    dark: 'rgb(255 255 255 / 0.8)',
    swatch: 'bg-black-80',
  },
  {
    name: 'black-40',
    figma: 'Black/40%',
    light: 'rgb(0 0 0 / 0.4)',
    dark: 'rgb(255 255 255 / 0.4)',
    swatch: 'bg-black-40',
  },
  {
    name: 'black-20',
    figma: 'Black/20%',
    light: 'rgb(0 0 0 / 0.2)',
    dark: 'rgb(255 255 255 / 0.2)',
    swatch: 'bg-black-20',
  },
  {
    name: 'black-10',
    figma: 'Black/10%',
    light: 'rgb(0 0 0 / 0.1)',
    dark: 'rgb(255 255 255 / 0.15)',
    swatch: 'bg-black-10',
    note: 'Default border colour.',
  },
  {
    name: 'black-4',
    figma: 'Black/4%',
    light: 'rgb(0 0 0 / 0.04)',
    dark: 'rgb(255 255 255 / 0.1)',
    swatch: 'bg-black-4',
  },
  {
    name: 'white',
    figma: 'White/100%',
    light: '#fff',
    dark: '#000',
    swatch: 'bg-white',
  },
  {
    name: 'white-80',
    figma: 'White/80%',
    light: 'rgb(255 255 255 / 0.8)',
    dark: 'rgb(0 0 0 / 0.8)',
    swatch: 'bg-white-80',
  },
  {
    name: 'white-40',
    figma: 'White/40%',
    light: 'rgb(255 255 255 / 0.4)',
    dark: 'rgb(0 0 0 / 0.4)',
    swatch: 'bg-white-40',
  },
  {
    name: 'white-20',
    figma: 'White/20%',
    light: 'rgb(255 255 255 / 0.2)',
    dark: 'rgb(0 0 0 / 0.2)',
    swatch: 'bg-white-20',
  },
  {
    name: 'white-10',
    figma: 'White/10%',
    light: 'rgb(255 255 255 / 0.1)',
    dark: 'rgb(0 0 0 / 0.1)',
    swatch: 'bg-white-10',
  },
  {
    name: 'white-4',
    figma: 'White/4%',
    light: 'rgb(255 255 255 / 0.04)',
    dark: 'rgb(0 0 0 / 0.04)',
    swatch: 'bg-white-4',
  },
  {
    name: 'background-1',
    figma: 'Background/1',
    light: '#fff',
    dark: '#333',
    swatch: 'bg-background-1',
  },
  {
    name: 'background-2',
    figma: 'Background/2',
    light: '#f9f9fa',
    dark: 'rgb(255 255 255 / 0.04)',
    swatch: 'bg-background-2',
  },
  {
    name: 'background-3',
    figma: 'Background/3',
    light: 'rgb(255 255 255 / 0.9)',
    dark: 'rgb(64 64 64 / 0.9)',
    swatch: 'bg-background-3',
  },
  {
    name: 'surface-1',
    figma: 'Surface/1',
    light: 'rgb(255 255 255 / 0.8)',
    dark: 'rgb(255 255 255 / 0.04)',
    swatch: 'bg-surface-1',
  },
  {
    name: 'surface-2',
    figma: 'Surface/2',
    light: 'rgb(0 0 0 / 0.03)',
    dark: 'rgb(0 0 0 / 0.1)',
    swatch: 'bg-surface-2',
  },
  {
    name: 'surface-3',
    figma: 'Surface/3',
    light: 'rgb(0 0 0 / 0.02)',
    dark: 'rgb(255 255 255 / 0.04)',
    swatch: 'bg-surface-3',
  },
  {
    name: 'color-1',
    figma: 'Color 1',
    light: '#e6f1fd',
    dark: '#e6f1fd',
    swatch: 'bg-color-1',
  },
  {
    name: 'color-2',
    figma: 'Color 2',
    light: '#edeefc',
    dark: '#edeefc',
    swatch: 'bg-color-2',
  },
  {
    name: 'static-white',
    figma: 'Static White/100%',
    light: '#fff',
    dark: '#fff',
    swatch: 'bg-static-white',
  },
  {
    name: 'static-black',
    figma: 'Static Black/100%',
    light: '#000',
    dark: '#000',
    swatch: 'bg-static-black',
  },
  {
    name: 'purple',
    figma: 'Secondary/Purple',
    light: '#b899eb',
    dark: '#b899eb',
    swatch: 'bg-purple',
  },
  {
    name: 'indigo',
    figma: 'Secondary/Indigo',
    light: '#adadfb',
    dark: '#adadfb',
    swatch: 'bg-indigo',
  },
  {
    name: 'blue',
    figma: 'Secondary/Blue',
    light: '#7dbbff',
    dark: '#7dbbff',
    swatch: 'bg-blue',
  },
  {
    name: 'cyan',
    figma: 'Secondary/Cyan',
    light: '#a0bce8',
    dark: '#a0bce8',
    swatch: 'bg-cyan',
  },
  {
    name: 'mint',
    figma: 'Secondary/Mint',
    light: '#6be6d3',
    dark: '#6be6d3',
    swatch: 'bg-mint',
  },
  {
    name: 'green',
    figma: 'Secondary/Green',
    light: '#71dd8c',
    dark: '#71dd8c',
    swatch: 'bg-green',
  },
  {
    name: 'yellow',
    figma: 'Secondary/Yellow',
    light: '#fc0',
    dark: '#fc0',
    swatch: 'bg-yellow',
  },
  {
    name: 'orange',
    figma: 'Secondary/Orange',
    light: '#ffb55b',
    dark: '#ffb55b',
    swatch: 'bg-orange',
  },
  {
    name: 'red',
    figma: 'Secondary/Red',
    light: '#ff4747',
    dark: '#ff4747',
    swatch: 'bg-red',
  },
  {
    name: 'indigo-text',
    figma: '—',
    light: '#5b5bd6',
    dark: '#adadfb',
    swatch: 'bg-indigo-text',
    note: 'Accessibility addition (not in the Figma kit): Secondary/Indigo is 2.07:1 on white, so indigo text is darker in light mode (5.37:1 on background-1); dark mode keeps the Figma indigo (6.11:1 on #333). Link, active Tag.',
  },
  {
    name: 'text-secondary',
    figma: '—',
    light: 'rgb(0 0 0 / 0.6)',
    dark: 'rgb(255 255 255 / 0.7)',
    swatch: 'bg-text-secondary',
    note: 'Accessibility addition (not in the Figma kit): Black/40% text is 2.85:1 on white, so secondary text (descriptions, captions, table headers, inactive tabs; the text-secondary utility) is Black/60% in light mode (5.74:1 on background-1, at least 5.5:1 on background-2, the Black/4% hover and the Color 1/2 tints) and White/70% in dark mode (7.08:1 on #333, at least 4.76:1 on the lightest popover surface).',
  },
  {
    name: 'red-text',
    figma: '—',
    light: '#d42020',
    dark: '#ff8080',
    swatch: 'bg-red-text',
    note: 'Accessibility addition (not in the Figma kit): Secondary/Red is 3.36:1 on white and 3.76:1 on #333, so error text (FormMessage, an invalid FormLabel) is #D42020 in light mode and #FF8080 in dark mode (5.21:1 on background-1 in both).',
  },
  {
    name: 'control-border',
    figma: 'Black/20%',
    light: 'var(--color-black-20)',
    dark: 'var(--color-black-20)',
    swatch: 'bg-control-border',
    resolved: {
      light: 'rgb(0 0 0 / 0.2)',
      dark: 'rgb(255 255 255 / 0.2)',
    },
    contrastMore: {
      light: 'rgb(0 0 0 / 0.5)',
      dark: 'rgb(255 255 255 / 0.5)',
    },
    note: 'Accessibility addition (not in the Figma kit): the boundary of form controls — the rings of unchecked Checkbox and Radio, the strokes of the text fields and the Select trigger, the Switch\'s off track. Contrast "standard" (the default): the Figma Black/20% (1.6:1 on background-1). Contrast "more" (prefers-contrast: more, data-contrast="more"): Black/50%, at least 3.79:1 on every surface and field fill (WCAG 1.4.11).',
  },
  {
    name: 'control-border-strong',
    figma: 'Black/40%',
    light: 'var(--color-black-40)',
    dark: 'var(--color-black-40)',
    swatch: 'bg-control-border-strong',
    resolved: {
      light: 'rgb(0 0 0 / 0.4)',
      dark: 'rgb(255 255 255 / 0.4)',
    },
    contrastMore: {
      light: 'rgb(0 0 0 / 0.8)',
      dark: 'rgb(255 255 255 / 0.8)',
    },
    note: 'Accessibility addition (not in the Figma kit): the hover and focus boundary of form controls (text field strokes, Checkbox and Radio rings, the Switch\'s off track), the Slider thumb\'s border, the Select chevron and the hovered Search icon. Contrast "standard" (the default): the Figma Black/40% (2.85:1). Contrast "more": Black/80% (12.6:1), stronger than control-border.',
  },
  {
    name: 'placeholder',
    figma: 'Black/20%',
    light: 'var(--color-black-20)',
    dark: 'var(--color-black-20)',
    swatch: 'bg-placeholder',
    resolved: {
      light: 'rgb(0 0 0 / 0.2)',
      dark: 'rgb(255 255 255 / 0.2)',
    },
    contrastMore: {
      light: 'rgb(0 0 0 / 0.6)',
      dark: 'rgb(255 255 255 / 0.75)',
    },
    note: 'Accessibility addition (not in the Figma kit): the placeholder text of the native text fields (Input, InputSmall, Textarea, Search) and the Search icon. Contrast "standard" (the default): the Figma Black/20% (1.6:1). Contrast "more": Black/60%, at least 5.25:1 on every field fill (WCAG 1.4.3).',
  },
]

/** Old colour names, kept as aliases until the next major. */
export const deprecatedColors: { name: string; use: string }[] = [
  {
    name: 'brand',
    use: 'primary',
  },
  {
    name: 'brand-hover',
    use: 'primary-hover-strong',
  },
  {
    name: 'bg1',
    use: 'background-1',
  },
  {
    name: 'bg2',
    use: 'background-2',
  },
  {
    name: 'bg3',
    use: 'color-1',
  },
  {
    name: 'bg4',
    use: 'color-2',
  },
  {
    name: 'bg5',
    use: 'surface-1',
  },
  {
    name: 'background',
    use: 'background-1',
  },
  {
    name: 'foreground',
    use: 'black',
  },
  {
    name: 'muted',
    use: 'black-4',
  },
  {
    name: 'muted-foreground',
    use: 'black-40',
  },
  {
    name: 'accent',
    use: 'black-10',
  },
  {
    name: 'accent-foreground',
    use: 'black',
  },
  {
    name: 'destructive',
    use: 'red',
  },
  {
    name: 'input',
    use: 'black-10',
  },
  {
    name: 'ring',
    use: 'primary',
  },
  {
    name: 'sidebar-border',
    use: 'black-10',
  },
  {
    name: 'white-border',
    use: 'black-10',
  },
]

/** `--font-sans`. */
export const fontFamily = 'Inter, sans-serif'

export const fontFeatureSettings = '"ss01" 1, "cv01" 1'

/** Figma text styles, largest first. */
export const textStyles: TextStyle[] = [
  {
    size: 64,
    lineHeight: 72,
    weights: [400, 600],
    utility: 'text-64',
  },
  {
    size: 48,
    lineHeight: 56,
    weights: [400, 600],
    utility: 'text-48',
  },
  {
    size: 32,
    lineHeight: 40,
    weights: [400, 600],
    utility: 'text-32',
  },
  {
    size: 24,
    lineHeight: 32,
    weights: [400, 600],
    utility: 'text-24',
  },
  {
    size: 18,
    lineHeight: 28,
    weights: [400, 600],
    utility: 'text-18',
  },
  {
    size: 16,
    lineHeight: 24,
    weights: [400, 600],
    utility: 'text-16',
  },
  {
    size: 14,
    lineHeight: 20,
    weights: [400, 600],
    utility: 'text-14',
  },
  {
    size: 12,
    lineHeight: 16,
    weights: [400, 600],
    utility: 'text-12',
  },
]

/** Figma "Corner Radius", in px. */
export const radii: { px: number; utility: string }[] = [
  {
    px: 4,
    utility: 'rounded-4',
  },
  {
    px: 8,
    utility: 'rounded-8',
  },
  {
    px: 12,
    utility: 'rounded-12',
  },
  {
    px: 16,
    utility: 'rounded-16',
  },
  {
    px: 20,
    utility: 'rounded-20',
  },
  {
    px: 24,
    utility: 'rounded-24',
  },
  {
    px: 28,
    utility: 'rounded-28',
  },
  {
    px: 32,
    utility: 'rounded-32',
  },
  {
    px: 40,
    utility: 'rounded-40',
  },
  {
    px: 48,
    utility: 'rounded-48',
  },
  {
    px: 80,
    utility: 'rounded-80',
  },
]

/** Figma effect styles. Their colours are raw values: they don't flip in dark mode. */
export const shadows: EffectToken[] = [
  {
    variable: '--shadow-1',
    figma: 'Drop shadow 1',
    value: '0 0.5px 0.5px 0 rgb(0 0 0 / 0.1)',
    utility: 'shadow-1',
  },
  {
    variable: '--shadow-2',
    figma: 'Drop shadow 2',
    value: '0 2px 4px 0 rgb(0 0 0 / 0.1)',
    utility: 'shadow-2',
  },
  {
    variable: '--shadow-focus',
    figma: 'Focus',
    value: '0 0 0 4px rgb(0 0 0 / 0.04)',
    utility: 'shadow-focus',
    note: 'Or ring-4 ring-focus, which composes with other shadows.',
  },
  {
    variable: '--shadow-glow',
    figma: 'Glow',
    value: '0 0 12px 8px rgb(255 255 255 / 0.2), 0 0 12px 8px rgb(0 0 0 / 0.2)',
    utility: 'shadow-glow',
  },
  {
    variable: '--shadow-glass-1',
    figma: 'Glass 1 (drop shadow part)',
    value: '0 4px 16px 0 rgb(0 0 0 / 0.04)',
    utility: 'shadow-glass-1',
  },
  {
    variable: '--shadow-glass-2',
    figma: 'Glass 2 (drop shadow part)',
    value: '0 8px 28px 0 rgb(0 0 0 / 0.1)',
    utility: 'shadow-glass-2',
  },
  {
    variable: '--inset-shadow-inner',
    figma: 'Inner shadow',
    value:
      'inset 1px 1.5px 4px 0 rgb(0 0 0 / 0.1), inset 1px 1.5px 4px 0 rgb(0 0 0 / 0.08), inset 0 -0.5px 1px 0 rgb(255 255 255 / 0.25), inset 0 -0.5px 1px 0 rgb(255 255 255 / 0.3)',
    utility: 'inset-shadow-inner',
  },
]

export const focusRing: EffectToken = {
  variable: '--ring-color-focus',
  figma: 'Focus',
  value: 'rgb(0 0 0 / 0.04)',
  utility: 'ring-4 ring-focus',
}

/** Figma background blurs: CSS blur is half the Figma value. */
export const blurs: EffectToken[] = [
  {
    variable: '--blur-bg-40',
    figma: 'Background blur 40',
    value: '20px',
    utility: 'backdrop-blur-bg-40',
  },
  {
    variable: '--blur-bg-100',
    figma: 'Background blur 100',
    value: '50px',
    utility: 'backdrop-blur-bg-100',
  },
]
