export const COLOR_SCHEME = {
	black: {
		5: "rgba(var(--color-black-5))",
		10: "rgba(var(--color-black-10))",
		20: "rgba(var(--color-black-20))",
		40: "rgba(var(--color-black-40))",
		80: "rgba(var(--color-black-80))",
		100: "rgba(var(--color-black-100))",
	},
	white: {
		5: "rgba(var(--color-white-5))",
		10: "rgba(var(--color-white-10))",
		20: "rgba(var(--color-white-20))",
		40: "rgba(var(--color-white-40))",
		80: "rgba(var(--color-white-80))",
		100: "rgba(var(--color-white-100))",
	},
	primary: {
		brand: "rgba(var(--color-primary-brand))",
		brandHover: "rgba(var(--color-primary-brand-hover))",
		blue: "rgba(var(--color-primary-blue))",
		purple: {
			DEFAULT: "rgba(var(--color-primary-purple))",
			50: "rgba(var(--color-primary-purple-50))",
		},
		light: "rgba(var(--color-primary-light))",
		background: "rgba(var(--color-primary-background))",
	},
	secondary: {
		blue: "rgba(var(--color-secondary-blue))",
		blueDarker: "rgba(var(--color-secondary-blue-darker))",
		blueLighter: "rgba(var(--color-secondary-blue-lighter))",
		cyan: "rgba(var(--color-secondary-cyan))",
		green: "rgba(var(--color-secondary-green))",
		greenDarker: "rgba(var(--color-secondary-green-darker))",
		greenLighter: "rgba(var(--color-secondary-green-lighter))",
		indigo: "rgba(var(--color-secondary-indigo))",
		indigoDarker: "rgba(var(--color-secondary-indigo-darker))",
		indigoLighter: "rgba(var(--color-secondary-indigo-lighter))",
		mint: "rgba(var(--color-secondary-mint))",
		orange: "rgba(var(--color-secondary-orange))",
		purple: "rgba(var(--color-secondary-purple))",
		red: "rgba(var(--color-secondary-red))",
		yellow: "rgba(var(--color-secondary-yellow))",
		yellowDarker: "rgba(var(--color-secondary-yellow-darker))",
		yellowLighter: "rgba(var(--color-secondary-yellow-lighter))",
	},
} as const;
