/*
 * Generated by `bun run tokens` (Terrazzo, scripts/terrazzo-plugin-snow-ui.ts)
 * from tokens/*.tokens.json. Do not edit: change the tokens and regenerate.
 */

/** The SnowUI token scales that tailwind-merge doesn't know by default. */
export const tokenScales = {
  text: ['12', '14', '16', '18', '24', '32', '48', '64'],
  radius: ['4', '8', '12', '16', '20', '24', '28', '32', '40', '48', '80'],
  shadow: ['1', '2', 'focus', 'glow', 'glass-1', 'glass-2'],
  'inset-shadow': ['inner'],
  blur: ['bg-40', 'bg-100'],
}
