/*
 * The SnowUI Figma kit draws its UI icons with Phosphor. @holakirr/snow-ui-icons
 * covers the kit's own icons (search, arrows, rise / fall, the logo…); the
 * rest come from @phosphor-icons/react. The `ssr` builds have no React
 * context, so they render in Server and client components alike, and one
 * import per icon keeps the bundles small.
 */

export { AddressBookIcon } from '@phosphor-icons/react/dist/ssr/AddressBook'
export { AppleLogoIcon } from '@phosphor-icons/react/dist/ssr/AppleLogo'
export { ArrowsLeftRightIcon } from '@phosphor-icons/react/dist/ssr/ArrowsLeftRight'
export { BellIcon } from '@phosphor-icons/react/dist/ssr/Bell'
export { BroadcastIcon } from '@phosphor-icons/react/dist/ssr/Broadcast'
export { BugBeetleIcon } from '@phosphor-icons/react/dist/ssr/BugBeetle'
export { ChartPieSliceIcon } from '@phosphor-icons/react/dist/ssr/ChartPieSlice'
export { ChatsTeardropIcon } from '@phosphor-icons/react/dist/ssr/ChatsTeardrop'
export { CheckIcon } from '@phosphor-icons/react/dist/ssr/Check'
export { ClockCounterClockwiseIcon } from '@phosphor-icons/react/dist/ssr/ClockCounterClockwise'
export { CreditCardIcon } from '@phosphor-icons/react/dist/ssr/CreditCard'
export { CurrencyCircleDollarIcon } from '@phosphor-icons/react/dist/ssr/CurrencyCircleDollar'
export { DesktopIcon } from '@phosphor-icons/react/dist/ssr/Desktop'
export { DotsThreeIcon } from '@phosphor-icons/react/dist/ssr/DotsThree'
export { EyeIcon } from '@phosphor-icons/react/dist/ssr/Eye'
export { EyeSlashIcon } from '@phosphor-icons/react/dist/ssr/EyeSlash'
export { FigmaLogoIcon } from '@phosphor-icons/react/dist/ssr/FigmaLogo'
export { FolderOpenIcon } from '@phosphor-icons/react/dist/ssr/FolderOpen'
export { FunnelIcon } from '@phosphor-icons/react/dist/ssr/Funnel'
export { GearSixIcon } from '@phosphor-icons/react/dist/ssr/GearSix'
export { GoogleLogoIcon } from '@phosphor-icons/react/dist/ssr/GoogleLogo'
export { HandPalmIcon } from '@phosphor-icons/react/dist/ssr/HandPalm'
export { IdentificationBadgeIcon } from '@phosphor-icons/react/dist/ssr/IdentificationBadge'
export { InstagramLogoIcon } from '@phosphor-icons/react/dist/ssr/InstagramLogo'
export { ListBulletsIcon } from '@phosphor-icons/react/dist/ssr/ListBullets'
export { MoonIcon } from '@phosphor-icons/react/dist/ssr/Moon'
export { NotebookIcon } from '@phosphor-icons/react/dist/ssr/Notebook'
export { PaletteIcon } from '@phosphor-icons/react/dist/ssr/Palette'
export { PlugIcon } from '@phosphor-icons/react/dist/ssr/Plug'
export { PlugsConnectedIcon } from '@phosphor-icons/react/dist/ssr/PlugsConnected'
export { PlusIcon } from '@phosphor-icons/react/dist/ssr/Plus'
export { ShieldCheckIcon } from '@phosphor-icons/react/dist/ssr/ShieldCheck'
export { ShoppingBagOpenIcon } from '@phosphor-icons/react/dist/ssr/ShoppingBagOpen'
export { SidebarSimpleIcon } from '@phosphor-icons/react/dist/ssr/SidebarSimple'
export { SignInIcon } from '@phosphor-icons/react/dist/ssr/SignIn'
export { SlackLogoIcon } from '@phosphor-icons/react/dist/ssr/SlackLogo'
export { StarIcon } from '@phosphor-icons/react/dist/ssr/Star'
export { SunIcon } from '@phosphor-icons/react/dist/ssr/Sun'
export { SunHorizonIcon } from '@phosphor-icons/react/dist/ssr/SunHorizon'
export { TextAaIcon } from '@phosphor-icons/react/dist/ssr/TextAa'
export { TranslateIcon } from '@phosphor-icons/react/dist/ssr/Translate'
export { TwitterLogoIcon } from '@phosphor-icons/react/dist/ssr/TwitterLogo'
export { UploadSimpleIcon } from '@phosphor-icons/react/dist/ssr/UploadSimple'
export { UserIcon } from '@phosphor-icons/react/dist/ssr/User'
export { UsersThreeIcon } from '@phosphor-icons/react/dist/ssr/UsersThree'
